// <auto-generated />
using System;
using Gymify.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gymify.Persistence.Migrations
{
    [DbContext(typeof(GymifyDbContext))]
    [Migration("20230429185115_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientGroupSession", b =>
                {
                    b.Property<int>("IdGroupSession")
                        .HasColumnType("int");

                    b.Property<string>("IdClient")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdGroupSession", "IdClient")
                        .HasName("ClientGroupSession_pk");

                    b.HasIndex("IdClient");

                    b.ToTable("ClientGroupSession", (string)null);
                });

            modelBuilder.Entity("CoachType", b =>
                {
                    b.Property<int>("IdCoachCategory")
                        .HasColumnType("int");

                    b.Property<string>("IdCoach")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCoachCategory", "IdCoach")
                        .HasName("CoachType_pk");

                    b.HasIndex("IdCoach");

                    b.ToTable("CoachType", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("Avatar")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.BodyPart", b =>
                {
                    b.Property<int>("IdBodyPart")
                        .HasColumnType("int");

                    b.Property<string>("BodyPartName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("IdBodyPart")
                        .HasName("BodyPart_pk");

                    b.ToTable("BodyPart", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Client", b =>
                {
                    b.Property<string>("IdClient")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdClient")
                        .HasName("Client_pk");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Coach", b =>
                {
                    b.Property<string>("IdCoach")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.HasKey("IdCoach")
                        .HasName("Coach_pk");

                    b.ToTable("Coach", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.CoachCategory", b =>
                {
                    b.Property<int>("IdCoachCategory")
                        .HasColumnType("int");

                    b.Property<string>("CoachCategoryName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("IdCoachCategory")
                        .HasName("CoachCategory_pk");

                    b.ToTable("CoachCategory", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.CoachHour", b =>
                {
                    b.Property<int>("CoachHourId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IdClient")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdCoach")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("CoachHourId")
                        .HasName("CoachHour_pk");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCoach");

                    b.ToTable("CoachHour", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.DifficultyLevel", b =>
                {
                    b.Property<int>("IdDifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("DifficultyLevelName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("IdDifficultyLevel")
                        .HasName("DifficultyLevel_pk");

                    b.ToTable("DifficultyLevel", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("IdEquipment")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("IdEquipment")
                        .HasName("Equipment_pk");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("IdExercise")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("GifUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("IdBodyPart")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipment")
                        .HasColumnType("int");

                    b.Property<int>("IdTarget")
                        .HasColumnType("int");

                    b.HasKey("IdExercise")
                        .HasName("Exercise_pk");

                    b.HasIndex("IdBodyPart");

                    b.HasIndex("IdEquipment");

                    b.HasIndex("IdTarget");

                    b.ToTable("Exercise", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.FavoriteCoach", b =>
                {
                    b.Property<int>("IdFavoriteCoach")
                        .HasColumnType("int");

                    b.Property<string>("IdClient")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdCoach")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdFavoriteCoach", "IdClient", "IdCoach")
                        .HasName("FavoriteCoach_pk");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCoach");

                    b.ToTable("FavoriteCoach", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.FavoriteExercise", b =>
                {
                    b.Property<int>("IdExercise")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FavoriteExercise1")
                        .HasColumnType("int")
                        .HasColumnName("FavoriteExercise");

                    b.HasKey("IdExercise", "IdUser", "FavoriteExercise1")
                        .HasName("FavoriteExercise_pk");

                    b.HasIndex("IdUser");

                    b.ToTable("FavoriteExercise", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.GroupSession", b =>
                {
                    b.Property<int>("IdGroupSession")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("IdCoach")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdPlace")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionEndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("SessionStartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.HasKey("IdGroupSession")
                        .HasName("GroupSession_pk");

                    b.HasIndex("IdCoach");

                    b.HasIndex("IdPlace");

                    b.ToTable("GroupSession", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Place", b =>
                {
                    b.Property<int>("IdPlace")
                        .HasColumnType("int");

                    b.Property<string>("Place1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Place");

                    b.HasKey("IdPlace")
                        .HasName("Place_pk");

                    b.ToTable("Place", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Target", b =>
                {
                    b.Property<int>("IdTarget")
                        .HasColumnType("int");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("IdTarget")
                        .HasName("Target_pk");

                    b.ToTable("Target", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Template", b =>
                {
                    b.Property<int>("IdTemplate")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedTime")
                        .HasColumnType("numeric(3, 0)");

                    b.Property<int>("IdDifficultyLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("IdTemplate")
                        .HasName("Template_pk");

                    b.HasIndex("IdDifficultyLevel");

                    b.ToTable("Template", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.TemplateExercise", b =>
                {
                    b.Property<int>("IdExercise")
                        .HasColumnType("int");

                    b.Property<int>("IdTemplate")
                        .HasColumnType("int");

                    b.Property<int>("IdTemplateExercise")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(160)
                        .IsUnicode(false)
                        .HasColumnType("varchar(160)");

                    b.Property<int>("NumberOfReps")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSets")
                        .HasColumnType("int");

                    b.HasKey("IdExercise", "IdTemplate", "IdTemplateExercise")
                        .HasName("TemplateExercise_pk");

                    b.HasIndex("IdTemplate");

                    b.ToTable("TemplateExercise", (string)null);
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Training", b =>
                {
                    b.Property<int>("IdTraining")
                        .HasColumnType("int");

                    b.Property<int>("IdTemplate")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("date");

                    b.Property<string>("TrainingName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("IdTraining")
                        .HasName("Training_pk");

                    b.HasIndex("IdTemplate");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.UserTraining", b =>
                {
                    b.Property<int>("IdTraining")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdUserTraining")
                        .HasColumnType("int");

                    b.HasKey("IdTraining", "IdUser", "IdUserTraining")
                        .HasName("UserTraining_pk");

                    b.HasIndex("IdUser");

                    b.ToTable("UserTraining", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClientGroupSession", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("ClientGroupSession_Client");

                    b.HasOne("Gymify.Domain.Entities.GroupSession", null)
                        .WithMany()
                        .HasForeignKey("IdGroupSession")
                        .IsRequired()
                        .HasConstraintName("ClientGroupSession_GroupSession");
                });

            modelBuilder.Entity("CoachType", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.Coach", null)
                        .WithMany()
                        .HasForeignKey("IdCoach")
                        .IsRequired()
                        .HasConstraintName("CoachType_Coach");

                    b.HasOne("Gymify.Domain.Entities.CoachCategory", null)
                        .WithMany()
                        .HasForeignKey("IdCoachCategory")
                        .IsRequired()
                        .HasConstraintName("CoachType_CoachCategory");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Client", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.AspNetUser", "IdClientNavigation")
                        .WithOne("Client")
                        .HasForeignKey("Gymify.Domain.Entities.Client", "IdClient")
                        .IsRequired()
                        .HasConstraintName("Client_AspNetUsers");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Coach", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.AspNetUser", "IdCoachNavigation")
                        .WithOne("Coach")
                        .HasForeignKey("Gymify.Domain.Entities.Coach", "IdCoach")
                        .IsRequired()
                        .HasConstraintName("Coach_AspNetUsers");

                    b.Navigation("IdCoachNavigation");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.CoachHour", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.Client", "IdClientNavigation")
                        .WithMany("CoachHours")
                        .HasForeignKey("IdClient")
                        .HasConstraintName("CoachHour_Client");

                    b.HasOne("Gymify.Domain.Entities.Coach", "IdCoachNavigation")
                        .WithMany("CoachHours")
                        .HasForeignKey("IdCoach")
                        .IsRequired()
                        .HasConstraintName("CoachHour_Coach");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdCoachNavigation");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.BodyPart", "IdBodyPartNavigation")
                        .WithMany("Exercises")
                        .HasForeignKey("IdBodyPart")
                        .IsRequired()
                        .HasConstraintName("Exercise_BodyPart");

                    b.HasOne("Gymify.Domain.Entities.Equipment", "IdEquipmentNavigation")
                        .WithMany("Exercises")
                        .HasForeignKey("IdEquipment")
                        .IsRequired()
                        .HasConstraintName("Exercise_Equipment");

                    b.HasOne("Gymify.Domain.Entities.Target", "IdTargetNavigation")
                        .WithMany("Exercises")
                        .HasForeignKey("IdTarget")
                        .IsRequired()
                        .HasConstraintName("Exercise_Target");

                    b.Navigation("IdBodyPartNavigation");

                    b.Navigation("IdEquipmentNavigation");

                    b.Navigation("IdTargetNavigation");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.FavoriteCoach", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.Client", "IdClientNavigation")
                        .WithMany("FavoriteCoaches")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FavoriteCoach_Client");

                    b.HasOne("Gymify.Domain.Entities.Coach", "IdCoachNavigation")
                        .WithMany("FavoriteCoaches")
                        .HasForeignKey("IdCoach")
                        .IsRequired()
                        .HasConstraintName("FavoriteCoach_Coach");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdCoachNavigation");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.FavoriteExercise", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.Exercise", "IdExerciseNavigation")
                        .WithMany("FavoriteExercises")
                        .HasForeignKey("IdExercise")
                        .IsRequired()
                        .HasConstraintName("UserExercise_Exercise");

                    b.HasOne("Gymify.Domain.Entities.AspNetUser", "IdUserNavigation")
                        .WithMany("FavoriteExercises")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FavoriteExercise_AspNetUsers");

                    b.Navigation("IdExerciseNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.GroupSession", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.Coach", "IdCoachNavigation")
                        .WithMany("GroupSessions")
                        .HasForeignKey("IdCoach")
                        .IsRequired()
                        .HasConstraintName("GroupSession_Coach");

                    b.HasOne("Gymify.Domain.Entities.Place", "IdPlaceNavigation")
                        .WithMany("GroupSessions")
                        .HasForeignKey("IdPlace")
                        .IsRequired()
                        .HasConstraintName("GroupSession_Place");

                    b.Navigation("IdCoachNavigation");

                    b.Navigation("IdPlaceNavigation");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Template", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.DifficultyLevel", "IdDifficultyLevelNavigation")
                        .WithMany("Templates")
                        .HasForeignKey("IdDifficultyLevel")
                        .IsRequired()
                        .HasConstraintName("Template_DifficultyLevel");

                    b.Navigation("IdDifficultyLevelNavigation");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.TemplateExercise", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.Exercise", "IdExerciseNavigation")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("IdExercise")
                        .IsRequired()
                        .HasConstraintName("Table_9_Exercise");

                    b.HasOne("Gymify.Domain.Entities.Template", "IdTemplateNavigation")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("IdTemplate")
                        .IsRequired()
                        .HasConstraintName("TemplateExercise_Template");

                    b.Navigation("IdExerciseNavigation");

                    b.Navigation("IdTemplateNavigation");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Training", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.Template", "IdTemplateNavigation")
                        .WithMany("Training")
                        .HasForeignKey("IdTemplate")
                        .IsRequired()
                        .HasConstraintName("Training_Template");

                    b.Navigation("IdTemplateNavigation");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.UserTraining", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.Training", "IdTrainingNavigation")
                        .WithMany("UserTrainings")
                        .HasForeignKey("IdTraining")
                        .IsRequired()
                        .HasConstraintName("UserTraining_Training");

                    b.HasOne("Gymify.Domain.Entities.AspNetUser", "IdUserNavigation")
                        .WithMany("UserTrainings")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("UserTraining_AspNetUsers");

                    b.Navigation("IdTrainingNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gymify.Domain.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Gymify.Domain.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gymify.Domain.Entities.AspNetUser", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Coach");

                    b.Navigation("FavoriteExercises");

                    b.Navigation("UserTrainings");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.BodyPart", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Client", b =>
                {
                    b.Navigation("CoachHours");

                    b.Navigation("FavoriteCoaches");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Coach", b =>
                {
                    b.Navigation("CoachHours");

                    b.Navigation("FavoriteCoaches");

                    b.Navigation("GroupSessions");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.DifficultyLevel", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("FavoriteExercises");

                    b.Navigation("TemplateExercises");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Place", b =>
                {
                    b.Navigation("GroupSessions");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Target", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Template", b =>
                {
                    b.Navigation("TemplateExercises");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Gymify.Domain.Entities.Training", b =>
                {
                    b.Navigation("UserTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
